server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registery: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:{serve.port}/eureka/